/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Categories */
    get: operations["list_categories_api_categories_get"];
    put?: never;
    /** Create Category */
    post: operations["create_category_api_categories_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Sources */
    get: operations["list_sources_api_sources_get"];
    put?: never;
    /** Create Source */
    post: operations["create_source_api_sources_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources/{source_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Source */
    get: operations["get_source_api_sources__source_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Source
     * @description 删除来源及其从属数据；受影响的未完成采集运行按剩余任务重算状态。
     */
    delete: operations["delete_source_api_sources__source_id__delete"];
    options?: never;
    head?: never;
    /** Update Source */
    patch: operations["update_source_api_sources__source_id__patch"];
    trace?: never;
  };
  "/api/sources/{source_id}/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Test Source */
    post: operations["test_source_api_sources__source_id__test_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources/{source_id}/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Source Health */
    get: operations["source_health_api_sources__source_id__health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collection/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Collection Run */
    post: operations["create_collection_run_api_collection_runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collection/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Collection Run
     * @description 读取所有来源汇总后的采集统计。
     */
    get: operations["get_collection_run_api_collection_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Messages */
    get: operations["list_messages_api_messages_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/messages/{message_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Message */
    get: operations["get_message_api_messages__message_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Message
     * @description 删除一条消息及其版本、译文、加工结果与相关任务。
     */
    delete: operations["delete_message_api_messages__message_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/messages/{message_id}/related": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Related Messages
     * @description 共享关键词的其他消息；没有关键词时返回空列表。
     */
    get: operations["related_messages_api_messages__message_id__related_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/messages/{message_id}/impact": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Message Impact
     * @description 删除影响面预览：确认弹层据此说明会删掉什么。
     */
    get: operations["message_impact_api_messages__message_id__impact_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/messages/bulk-delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk Delete Messages
     * @description 批量删除消息；dry_run 只返回影响面。
     */
    post: operations["bulk_delete_messages_api_messages_bulk_delete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/messages/{message_id}/translate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Translate Message */
    post: operations["translate_message_api_messages__message_id__translate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/messages/{message_id}/enrich": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enrich Message */
    post: operations["enrich_message_api_messages__message_id__enrich_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/keywords": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Keywords
     * @description 词表：按出现次数排序的规范词，默认折叠只出现一次的词。
     */
    get: operations["list_keywords_api_keywords_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/keywords/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Keyword Overview
     * @description 概览：规模、类型构成、长尾、趋势、来源分布与覆盖与回填进度。
     */
    get: operations["keyword_overview_api_keywords_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/keywords/rebuild": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rebuild Index
     * @description 按已存的加工结果重建关键词索引；不调用模型，可重复执行。
     */
    post: operations["rebuild_index_api_keywords_rebuild_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/keywords/backfill": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Backfill Keywords
     * @description 为没有加工结果的存量消息入队；先用 dry_run 看条数再执行。
     */
    post: operations["backfill_keywords_api_keywords_backfill_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/keywords/merges": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Merges
     * @description 最近的合并记录；已撤销的记录也在列表里。
     */
    get: operations["list_merges_api_keywords_merges_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/keywords/merge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Merge Keywords
     * @description 合并同指写法；dry_run 只返回影响面。
     */
    post: operations["merge_keywords_api_keywords_merge_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/keywords/merges/{merge_id}/undo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Undo Merge
     * @description 撤销一次合并；别名按原值回填。
     */
    post: operations["undo_merge_api_keywords_merges__merge_id__undo_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Task */
    get: operations["get_task_api_tasks__task_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Task
     * @description 删除已结束的任务；排队与运行中的任务拒绝删除。
     */
    delete: operations["delete_task_api_tasks__task_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tasks
     * @description 查询任务列表。
     */
    get: operations["list_tasks_api_tasks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Retry Task
     * @description 重新排队失败任务。
     */
    post: operations["retry_task_api_tasks__task_id__retry_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/clear-failed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Clear Failed Tasks
     * @description 清理全部失败任务；dry_run 先看条数。
     */
    post: operations["clear_failed_tasks_api_tasks_clear_failed_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/providers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Providers */
    get: operations["list_providers_api_llm_providers_get"];
    put?: never;
    /** Create Provider */
    post: operations["create_provider_api_llm_providers_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/providers/{provider_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Provider */
    patch: operations["update_provider_api_llm_providers__provider_id__patch"];
    trace?: never;
  };
  "/api/llm/providers/{provider_id}/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Test Provider Connection
     * @description 试跑一次最小结构化调用，验证 Base URL、模型与 Key 是否可用。
     */
    post: operations["test_provider_connection_api_llm_providers__provider_id__test_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/providers/{provider_id}/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Provider Model */
    post: operations["create_provider_model_api_llm_providers__provider_id__models_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/providers/{provider_id}/models/{model_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Provider Model */
    patch: operations["update_provider_model_api_llm_providers__provider_id__models__model_id__patch"];
    trace?: never;
  };
  "/api/llm/providers/{provider_id}/keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Provider Key */
    post: operations["create_provider_key_api_llm_providers__provider_id__keys_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/providers/{provider_id}/keys/{key_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Provider Key */
    patch: operations["update_provider_key_api_llm_providers__provider_id__keys__key_id__patch"];
    trace?: never;
  };
  "/api/llm/prompts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Prompts
     * @description 列出提示词版本；可按任务类型过滤。
     */
    get: operations["list_prompts_api_llm_prompts_get"];
    put?: never;
    /**
     * Create Prompt
     * @description 新建提示词版本；同 prompt_key 的版本号自动递增。
     */
    post: operations["create_prompt_api_llm_prompts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/prompts/specs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Specs
     * @description 任务规格：界面用它渲染占位符提示与输出字段要求。
     */
    get: operations["list_specs_api_llm_prompts_specs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/prompts/compile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Compile Prompt Template
     * @description 编译校验与样例预览；不写库。
     */
    post: operations["compile_prompt_template_api_llm_prompts_compile_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/prompts/{prompt_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Prompt */
    get: operations["get_prompt_api_llm_prompts__prompt_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Prompt
     * @description 删除从未被使用过的版本；已被引用或正在启用的版本会被拒绝。
     */
    delete: operations["delete_prompt_api_llm_prompts__prompt_id__delete"];
    options?: never;
    head?: never;
    /**
     * Update Prompt
     * @description 就地编辑未被使用过的版本；版本串不变，因此审计仍然指得回这条记录。
     */
    patch: operations["update_prompt_api_llm_prompts__prompt_id__patch"];
    trace?: never;
  };
  "/api/llm/prompts/{prompt_id}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Activate Prompt
     * @description 启用版本；同任务类型的其它启用版本自动归档。
     */
    post: operations["activate_prompt_api_llm_prompts__prompt_id__activate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/prompts/{prompt_id}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archive Prompt */
    post: operations["archive_prompt_api_llm_prompts__prompt_id__archive_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/prompts/{prompt_id}/usage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Prompt Usage
     * @description 该版本的使用情况；界面据此决定能否就地编辑或删除。
     */
    get: operations["get_prompt_usage_api_llm_prompts__prompt_id__usage_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/prompts/{prompt_id}/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Test Prompt
     * @description 用样例输入试跑；会消耗一次真实模型调用，只写调用审计。
     */
    post: operations["test_prompt_api_llm_prompts__prompt_id__test_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task-settings/{scope}/{scope_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Task Settings
     * @description 某来源或分类的任务分配；带生效值与来源层级。
     */
    get: operations["get_task_settings_api_task_settings__scope___scope_id__get"];
    /**
     * Replace Task Settings
     * @description 整组覆盖任务分配；空值表示继承上一层。
     */
    put: operations["replace_task_settings_api_task_settings__scope___scope_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * CategoryCreateRequest
     * @description 创建分类请求。
     */
    CategoryCreateRequest: {
      /** Name */
      name: string;
      /** Slug */
      slug?: string | null;
    };
    /**
     * CategoryResponse
     * @description 分类响应。
     */
    CategoryResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Is Builtin */
      is_builtin: boolean;
      /** Is Active */
      is_active: boolean;
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
    };
    /**
     * CollectionRunDetailResponse
     * @description 采集运行统计。
     */
    CollectionRunDetailResponse: {
      /** Id */
      id: string;
      /** Source Ids */
      source_ids: string[];
      /** Status */
      status: string;
      /** Requested At */
      requested_at: number;
      /** Completed At */
      completed_at: number | null;
      /** Created Count */
      created_count: number;
      /** Updated Count */
      updated_count: number;
      /** Skipped Count */
      skipped_count: number;
      /** Failed Count */
      failed_count: number;
    };
    /**
     * CollectionRunRequest
     * @description 创建采集运行请求。
     */
    CollectionRunRequest: {
      /** Source Ids */
      source_ids?: string[];
      /**
       * All Enabled
       * @default false
       */
      all_enabled: boolean;
    };
    /**
     * CollectionRunResponse
     * @description 采集运行响应。
     */
    CollectionRunResponse: {
      /** Id */
      id: string;
      /** Source Ids */
      source_ids: string[];
      /** Status */
      status: string;
      /** Requested At */
      requested_at: number;
      /** Task Ids */
      task_ids: string[];
    };
    /**
     * ConnectionTestRequest
     * @description 连接测试请求；不填模型时使用第一个启用模型。
     */
    ConnectionTestRequest: {
      /** Model */
      model?: string | null;
    };
    /**
     * ConnectionTestResponse
     * @description 连接测试响应；只返回密钥掩码与模型回复片段，不返回密钥值。
     */
    ConnectionTestResponse: {
      /** Ok */
      ok: boolean;
      /** Model */
      model: string;
      /** Key Masked */
      key_masked: string;
      /** Latency Ms */
      latency_ms: number;
      /** Total Tokens */
      total_tokens: number;
      /** Error Code */
      error_code: string | null;
      /** Error Message */
      error_message: string | null;
      /**
       * Reply
       * @default
       */
      reply: string;
    };
    /**
     * EnrichmentResponse
     * @description 内容加工结果响应。
     */
    EnrichmentResponse: {
      /** Id */
      id: string;
      /** Message Version Id */
      message_version_id: string;
      /** Status */
      status: string;
      /** Title */
      title: string | null;
      /** Summary */
      summary: string | null;
      /** Keywords */
      keywords: components["schemas"]["KeywordResponse"][];
      /** Provider Id */
      provider_id: string | null;
      /** Key Masked */
      key_masked: string | null;
      /** Model */
      model: string | null;
      /** Prompt Version */
      prompt_version: string;
      /** Task Id */
      task_id: string | null;
      /** Error Code */
      error_code: string | null;
      /** Error Message */
      error_message: string | null;
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description 来源健康检查响应。
     */
    HealthResponse: {
      /** Id */
      id: string;
      /** Source Id */
      source_id: string;
      /** Checked At */
      checked_at: number;
      /** Http Status */
      http_status: number | null;
      /** Latency Ms */
      latency_ms: number | null;
      /** Parse Success */
      parse_success: boolean;
      /** Entry Count */
      entry_count: number;
      /** Error Code */
      error_code: string | null;
      /** Error Message */
      error_message: string | null;
    };
    /**
     * KeywordBackfillRequest
     * @description 存量回填请求；dry_run 只统计候选条数，不入队。
     */
    KeywordBackfillRequest: {
      /** Source Id */
      source_id?: string | null;
      /**
       * Limit
       * @default 50
       */
      limit: number;
      /**
       * Dry Run
       * @default false
       */
      dry_run: boolean;
    };
    /**
     * KeywordBackfillResponse
     * @description 回填结果；reasons 是去重后的跳过原因。
     */
    KeywordBackfillResponse: {
      /** Candidates */
      candidates: number;
      /** Enqueued */
      enqueued: number;
      /** Skipped */
      skipped: number;
      /** Reasons */
      reasons: string[];
    };
    /**
     * KeywordBucketResponse
     * @description 长尾分布的一档。
     */
    KeywordBucketResponse: {
      /** Label */
      label: string;
      /** Terms */
      terms: number;
    };
    /**
     * KeywordEntryResponse
     * @description 词表一行：规范词、展示写法、规模与首末出现时间。
     */
    KeywordEntryResponse: {
      /** Key */
      key: string;
      /** Text */
      text: string;
      /** Kind */
      kind: string;
      /** Mentions */
      mentions: number;
      /** Sources */
      sources: number;
      /** First Seen At */
      first_seen_at: number;
      /** Last Seen At */
      last_seen_at: number;
      /** Aliases */
      aliases: string[];
    };
    /**
     * KeywordKindStatResponse
     * @description 某一类型的关键词规模。
     */
    KeywordKindStatResponse: {
      /** Kind */
      kind: string;
      /** Terms */
      terms: number;
      /** Mentions */
      mentions: number;
    };
    /**
     * KeywordListResponse
     * @description 词表分页结果。
     */
    KeywordListResponse: {
      /** Items */
      items: components["schemas"]["KeywordEntryResponse"][];
      /** Total */
      total: number;
    };
    /**
     * KeywordMergePreviewResponse
     * @description 合并影响面：合并后的词频、受影响消息数与全部写法。
     */
    KeywordMergePreviewResponse: {
      /** Target */
      target: string;
      /** Sources */
      sources: string[];
      /** Forms */
      forms: components["schemas"]["KeywordResponse"][];
      /** Mentions */
      mentions: number;
      /** Messages */
      messages: number;
    };
    /**
     * KeywordMergeRecordResponse
     * @description 一次合并的记录；已撤销的记录保留供审计。
     */
    KeywordMergeRecordResponse: {
      /** Id */
      id: string;
      /** Target Key */
      target_key: string;
      /** Target Raw */
      target_raw: string;
      /** Members */
      members: components["schemas"]["KeywordResponse"][];
      /** Messages */
      messages: number;
      /** Created At */
      created_at: number;
      /** Undone At */
      undone_at: number | null;
    };
    /**
     * KeywordMergeRequest
     * @description 合并请求；dry_run 只返回影响面，不写别名。
     */
    KeywordMergeRequest: {
      /** Keys */
      keys: string[];
      /** Target */
      target: string;
      /**
       * Dry Run
       * @default false
       */
      dry_run: boolean;
    };
    /**
     * KeywordMergeResponse
     * @description 合并结果：影响面，以及执行后的记录（dry_run 时为空）。
     */
    KeywordMergeResponse: {
      record: components["schemas"]["KeywordMergeRecordResponse"] | null;
      preview: components["schemas"]["KeywordMergePreviewResponse"];
    };
    /**
     * KeywordOverviewResponse
     * @description 概览：规模、分布与覆盖；字段含义见 KeywordOverview。
     */
    KeywordOverviewResponse: {
      /** Messages */
      messages: number;
      /** Enriched */
      enriched: number;
      /** Pending */
      pending: number;
      /** Terms */
      terms: number;
      /** Mentions */
      mentions: number;
      /** Singletons */
      singletons: number;
      /** Average Per Message */
      average_per_message: number;
      /** Aliases */
      aliases: number;
      /** Merges */
      merges: number;
      /** Kinds */
      kinds: components["schemas"]["KeywordKindStatResponse"][];
      /** Long Tail */
      long_tail: components["schemas"]["KeywordBucketResponse"][];
      /** Trend */
      trend: components["schemas"]["KeywordTrendPointResponse"][];
      /** Sources */
      sources: components["schemas"]["KeywordSourceStatResponse"][];
      /** Tasks Queued */
      tasks_queued: number;
      /** Tasks Running */
      tasks_running: number;
      /** Tasks Succeeded */
      tasks_succeeded: number;
      /** Tasks Failed */
      tasks_failed: number;
    };
    /**
     * KeywordRebuildResponse
     * @description 关键词索引重建结果：写入的关系表行数。
     */
    KeywordRebuildResponse: {
      /** Indexed */
      indexed: number;
    };
    /**
     * KeywordResponse
     * @description 一条检索关键词；text 用于展示，kind 用于检索优先级与界面标注。
     */
    KeywordResponse: {
      /** Text */
      text: string;
      /** Kind */
      kind: string;
    };
    /**
     * KeywordSourceStatResponse
     * @description 来源维度的关键词规模。
     */
    KeywordSourceStatResponse: {
      /** Source Id */
      source_id: string;
      /** Source Name */
      source_name: string;
      /** Terms */
      terms: number;
      /** Mentions */
      mentions: number;
      /** Top */
      top: components["schemas"]["KeywordResponse"][];
    };
    /**
     * KeywordTrendPointResponse
     * @description 某一天的关键词产出。
     */
    KeywordTrendPointResponse: {
      /** Day */
      day: string;
      /** Mentions */
      mentions: number;
      /** New Terms */
      new_terms: number;
    };
    /**
     * KeywordUndoResponse
     * @description 撤销结果：恢复的别名行数。
     */
    KeywordUndoResponse: {
      /** Restored */
      restored: number;
    };
    /**
     * MessageBulkDeleteRequest
     * @description 批量删除请求；dry_run 只返回影响面。
     */
    MessageBulkDeleteRequest: {
      /** Message Ids */
      message_ids: string[];
      /**
       * Dry Run
       * @default false
       */
      dry_run: boolean;
    };
    /**
     * MessageDeletionResponse
     * @description 删除影响面或删除结果；两种场景共用同一形状。
     */
    MessageDeletionResponse: {
      /** Messages */
      messages: number;
      /** Versions */
      versions: number;
      /** Translations */
      translations: number;
      /** Enrichments */
      enrichments: number;
      /** Tasks */
      tasks: number;
    };
    /**
     * MessageDetailResponse
     * @description 消息详情响应。
     */
    MessageDetailResponse: {
      /** Id */
      id: string;
      /** Source Id */
      source_id: string;
      /** External Id */
      external_id: string;
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
      /** Versions */
      versions: components["schemas"]["MessageVersionResponse"][];
    };
    /**
     * MessageListResponse
     * @description 消息列表响应。
     */
    MessageListResponse: {
      /** Items */
      items: components["schemas"]["MessageResponse"][];
      /** Total */
      total: number;
    };
    /**
     * MessageResponse
     * @description 消息列表里的一行：消息本体与它的最新版本。
     */
    MessageResponse: {
      /** Id */
      id: string;
      /** Source Id */
      source_id: string;
      /** External Id */
      external_id: string;
      /** Updated At */
      updated_at: number;
      latest_version: components["schemas"]["MessageVersionResponse"] | null;
    };
    /**
     * MessageVersionResponse
     * @description 消息版本响应。
     */
    MessageVersionResponse: {
      /** Id */
      id: string;
      /** Message Id */
      message_id: string;
      /** Version Number */
      version_number: number;
      /** Title */
      title: string;
      /** Summary */
      summary: string;
      /** Content */
      content: string;
      /** Url */
      url: string;
      /** Published At */
      published_at: number | null;
      /** Collected At */
      collected_at: number;
      /** Language */
      language: string;
      /** Content Hash */
      content_hash: string;
      /** Translations */
      translations: components["schemas"]["TranslationResponse"][];
      /** Enrichments */
      enrichments: components["schemas"]["EnrichmentResponse"][];
      translation_task?: components["schemas"]["TaskResponse"] | null;
      enrichment_task?: components["schemas"]["TaskResponse"] | null;
    };
    /**
     * PromptCompileIssue
     * @description 一条编译问题。
     */
    PromptCompileIssue: {
      /** Field */
      field: string;
      /** Message */
      message: string;
    };
    /**
     * PromptCompileRequest
     * @description 编译校验请求；只校验和预览，不写库。
     */
    PromptCompileRequest: {
      /** Task Kind */
      task_kind: string;
      /**
       * System Template
       * @default
       */
      system_template: string;
      /**
       * User Template
       * @default
       */
      user_template: string;
      sample?: components["schemas"]["PromptSampleRequest"] | null;
    };
    /**
     * PromptCompileResponse
     * @description 编译结果：问题清单与样例渲染结果。
     */
    PromptCompileResponse: {
      /** Ok */
      ok: boolean;
      /** Errors */
      errors: components["schemas"]["PromptCompileIssue"][];
      /** Warnings */
      warnings: components["schemas"]["PromptCompileIssue"][];
      /** System */
      system: string;
      /** User */
      user: string;
      /** Variables */
      variables: string[];
    };
    /**
     * PromptCreateRequest
     * @description 新建提示词版本请求；编译不通过会被拒绝。
     */
    PromptCreateRequest: {
      /** Task Kind */
      task_kind: string;
      /** Prompt Key */
      prompt_key: string;
      /**
       * Name
       * @default
       */
      name: string;
      /**
       * System Template
       * @default
       */
      system_template: string;
      /** User Template */
      user_template: string;
      /**
       * Note
       * @default
       */
      note: string;
    };
    /**
     * PromptResponse
     * @description 提示词版本响应。
     */
    PromptResponse: {
      /** Id */
      id: string;
      /** Task Kind */
      task_kind: string;
      /** Prompt Key */
      prompt_key: string;
      /** Version */
      version: number;
      /** Version String */
      version_string: string;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /** System Template */
      system_template: string;
      /** User Template */
      user_template: string;
      /** Note */
      note: string;
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
    };
    /**
     * PromptSampleRequest
     * @description 编译预览与试跑的样例输入。
     */
    PromptSampleRequest: {
      /**
       * Title
       * @default
       */
      title: string;
      /**
       * Summary
       * @default
       */
      summary: string;
      /**
       * Content
       * @default
       */
      content: string;
    };
    /**
     * PromptTestRequest
     * @description 试跑请求；用真实消息或手填样例，会消耗一次模型调用。
     */
    PromptTestRequest: {
      /** Message Version Id */
      message_version_id?: string | null;
      sample?: components["schemas"]["PromptSampleRequest"] | null;
      /** Model */
      model?: string | null;
    };
    /**
     * PromptTestResponse
     * @description 试跑结果；只返回密钥掩码与结构化输出。
     */
    PromptTestResponse: {
      /** Ok */
      ok: boolean;
      /** Model */
      model: string;
      /** Key Masked */
      key_masked: string;
      /** Latency Ms */
      latency_ms: number;
      /** Total Tokens */
      total_tokens: number;
      /** System */
      system: string;
      /** User */
      user: string;
      /** Output */
      output: {
        [key: string]: unknown;
      };
      /** Error Code */
      error_code: string | null;
      /** Error Message */
      error_message: string | null;
    };
    /**
     * PromptUpdateRequest
     * @description 就地编辑请求；任务类型、业务键与版本号不变，名称留空时回落到业务键。
     */
    PromptUpdateRequest: {
      /**
       * Name
       * @default
       */
      name: string;
      /**
       * System Template
       * @default
       */
      system_template: string;
      /** User Template */
      user_template: string;
      /**
       * Note
       * @default
       */
      note: string;
    };
    /**
     * PromptUsageResponse
     * @description 提示词版本的使用情况；界面据此决定能否就地编辑或删除。
     *
     *     `used` 为真时只能另存新版本或归档；`bindings` 是来源与分类对该版本的绑定条数。
     */
    PromptUsageResponse: {
      /** Used */
      used: boolean;
      /** Calls */
      calls: number;
      /** Results */
      results: number;
      /** Tasks */
      tasks: number;
      /** Bindings */
      bindings: number;
    };
    /**
     * ProviderCreateRequest
     * @description 创建 provider 请求；protocol 省略时用 OpenAI 兼容协议。
     */
    ProviderCreateRequest: {
      /** Name */
      name: string;
      /** Base Url */
      base_url: string;
      /**
       * Protocol
       * @default chat_completions
       */
      protocol: string;
      /**
       * Timeout Seconds
       * @default 60
       */
      timeout_seconds: number;
      /** Session Header Name */
      session_header_name?: string | null;
      /** Extra Headers */
      extra_headers?: {
        [key: string]: string;
      };
    };
    /**
     * ProviderKeyCreateRequest
     * @description 录入 API Key 请求；密钥值只写入本机数据库。
     */
    ProviderKeyCreateRequest: {
      /** Secret */
      secret: string;
      /**
       * Priority
       * @default 100
       */
      priority: number;
    };
    /**
     * ProviderKeyPatchRequest
     * @description 更新 API Key 请求。
     */
    ProviderKeyPatchRequest: {
      /** Secret */
      secret?: string | null;
      /** Priority */
      priority?: number | null;
      /** Enabled */
      enabled?: boolean | null;
    };
    /**
     * ProviderKeyResponse
     * @description API Key 响应；只返回掩码，禁止返回密钥值。
     */
    ProviderKeyResponse: {
      /** Id */
      id: string;
      /** Provider Id */
      provider_id: string;
      /** Masked */
      masked: string;
      /** Priority */
      priority: number;
      /** Enabled */
      enabled: boolean;
      /** Cooldown Until */
      cooldown_until: number | null;
      /** Last Status */
      last_status: string | null;
    };
    /**
     * ProviderModelCreateRequest
     * @description 在 provider 下新增模型候选请求。
     */
    ProviderModelCreateRequest: {
      /** Model */
      model: string;
      /**
       * Priority
       * @default 100
       */
      priority: number;
    };
    /**
     * ProviderModelPatchRequest
     * @description 更新模型候选请求。
     */
    ProviderModelPatchRequest: {
      /** Model */
      model?: string | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Priority */
      priority?: number | null;
    };
    /**
     * ProviderModelResponse
     * @description 模型候选响应。
     */
    ProviderModelResponse: {
      /** Id */
      id: string;
      /** Provider Id */
      provider_id: string;
      /** Model */
      model: string;
      /** Enabled */
      enabled: boolean;
      /** Priority */
      priority: number;
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
    };
    /**
     * ProviderPatchRequest
     * @description 更新 provider 请求。
     */
    ProviderPatchRequest: {
      /** Name */
      name?: string | null;
      /** Base Url */
      base_url?: string | null;
      /** Protocol */
      protocol?: string | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Timeout Seconds */
      timeout_seconds?: number | null;
      /** Session Header Name */
      session_header_name?: string | null;
      /** Extra Headers */
      extra_headers?: {
        [key: string]: string;
      };
    };
    /**
     * ProviderResponse
     * @description provider 响应。
     */
    ProviderResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Base Url */
      base_url: string;
      /** Protocol */
      protocol: string;
      /** Enabled */
      enabled: boolean;
      /** Timeout Seconds */
      timeout_seconds: number;
      /** Session Header Name */
      session_header_name: string | null;
      /** Keys */
      keys: components["schemas"]["ProviderKeyResponse"][];
      /** Models */
      models: components["schemas"]["ProviderModelResponse"][];
      /** Extra Headers */
      extra_headers: {
        [key: string]: string;
      };
    };
    /**
     * RelatedMessageResponse
     * @description 相关消息；shared 是双方共有的关键词，按实体优先排列。
     */
    RelatedMessageResponse: {
      /** Message Id */
      message_id: string;
      /** Source Id */
      source_id: string;
      /** Version Id */
      version_id: string;
      /** Title */
      title: string;
      /** Published At */
      published_at: number | null;
      /** Collected At */
      collected_at: number;
      /** Shared */
      shared: components["schemas"]["KeywordResponse"][];
    };
    /**
     * SourceCreateRequest
     * @description 创建来源请求。
     */
    SourceCreateRequest: {
      /** Name */
      name: string;
      /** Url */
      url: string;
      /**
       * Platform
       * @default
       */
      platform: string;
      /**
       * Language
       * @default auto
       */
      language: string;
      /** Category Id */
      category_id: string;
      /**
       * Time Offset Minutes
       * @default 0
       */
      time_offset_minutes: number;
    };
    /**
     * SourceDeleteResponse
     * @description 删除来源响应；deleted_messages 为随之删除的消息条数。
     */
    SourceDeleteResponse: {
      /** Deleted Messages */
      deleted_messages: number;
    };
    /**
     * SourceDetailResponse
     * @description 来源详情响应。
     */
    SourceDetailResponse: {
      source: components["schemas"]["SourceResponse"];
      /** Health */
      health: components["schemas"]["HealthResponse"][];
      /**
       * Message Count
       * @default 0
       */
      message_count: number;
      latest_collection?:
        components["schemas"]["CollectionRunDetailResponse"] | null;
    };
    /**
     * SourceListResponse
     * @description 来源列表响应。
     */
    SourceListResponse: {
      /** Items */
      items: components["schemas"]["SourceResponse"][];
      /** Total */
      total: number;
    };
    /**
     * SourcePatchRequest
     * @description 更新来源请求。
     */
    SourcePatchRequest: {
      /** Name */
      name?: string | null;
      /** Url */
      url?: string | null;
      /** Platform */
      platform?: string | null;
      /** Language */
      language?: string | null;
      /** Category Id */
      category_id?: string | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Time Offset Minutes */
      time_offset_minutes?: number | null;
    };
    /**
     * SourceResponse
     * @description 来源响应。
     */
    SourceResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Url */
      url: string;
      /** Platform */
      platform: string;
      /** Language */
      language: string;
      /** Category Id */
      category_id: string;
      /** Enabled */
      enabled: boolean;
      /** Time Offset Minutes */
      time_offset_minutes: number;
      /** Feed Title */
      feed_title: string | null;
      /** Feed Link */
      feed_link: string | null;
      /** Feed Description */
      feed_description: string | null;
      /** Feed Language */
      feed_language: string | null;
      /** Feed Author */
      feed_author: string | null;
      /** Feed Updated At */
      feed_updated_at: string | null;
      /** Source Type */
      source_type: string;
      /** Metadata */
      metadata: {
        [key: string]: unknown;
      };
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
      latest_health?: components["schemas"]["HealthResponse"] | null;
      /** Last Success At */
      last_success_at?: number | null;
    };
    /**
     * SourceTestResponse
     * @description 来源测试响应。
     */
    SourceTestResponse: {
      source: components["schemas"]["SourceResponse"];
      health: components["schemas"]["HealthResponse"];
    };
    /**
     * TaskClearFailedRequest
     * @description 清理失败任务请求；dry_run 只返回条数。
     */
    TaskClearFailedRequest: {
      /**
       * Dry Run
       * @default false
       */
      dry_run: boolean;
    };
    /**
     * TaskDeletionResponse
     * @description 清理任务的结果：命中多少条、实际删除多少条。
     */
    TaskDeletionResponse: {
      /** Candidates */
      candidates: number;
      /** Deleted */
      deleted: number;
    };
    /**
     * TaskListResponse
     * @description 任务列表响应。
     */
    TaskListResponse: {
      /** Items */
      items: components["schemas"]["TaskResponse"][];
      /** Total */
      total: number;
    };
    /**
     * TaskResponse
     * @description 任务状态响应。
     *
     *     model / prompt_version 来自非敏感的任务快照；target_* 由任务列表的服务层解析
     *     （消息标题或来源名），嵌入在消息详情里的任务不填目标，因此给默认值。
     */
    TaskResponse: {
      /** Id */
      id: string;
      /** Task Type */
      task_type: string;
      /** Idempotency Key */
      idempotency_key: string;
      /** Status */
      status: string;
      /** Attempts */
      attempts: number;
      /** Lease Until */
      lease_until: number | null;
      /** Input Version Id */
      input_version_id: string | null;
      /** Output Version Id */
      output_version_id: string | null;
      /** Error Code */
      error_code: string | null;
      /** Error Message */
      error_message: string | null;
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
      /** Model */
      model?: string | null;
      /** Prompt Version */
      prompt_version?: string | null;
      /**
       * Target Kind
       * @default
       */
      target_kind: string;
      /** Target Id */
      target_id?: string | null;
      /**
       * Target Label
       * @default
       */
      target_label: string;
    };
    /**
     * TaskSettingItem
     * @description 单个任务类型的分配；enabled 与 prompt_id 为空表示继承上一层。
     */
    TaskSettingItem: {
      /** Task Kind */
      task_kind: string;
      /** Enabled */
      enabled?: boolean | null;
      /** Prompt Id */
      prompt_id?: string | null;
    };
    /**
     * TaskSettingResponse
     * @description 任务分配响应；带生效值与来源层级，便于界面显示"继承"还是"已覆盖"。
     */
    TaskSettingResponse: {
      /** Task Kind */
      task_kind: string;
      /** Label */
      label: string;
      /** Enabled */
      enabled: boolean | null;
      /** Prompt Id */
      prompt_id: string | null;
      /** Effective Enabled */
      effective_enabled: boolean;
      /** Effective Prompt Id */
      effective_prompt_id: string | null;
      /** Effective Prompt Version */
      effective_prompt_version: string | null;
      /** Scope */
      scope: string;
    };
    /**
     * TaskSettingsUpdateRequest
     * @description 整组覆盖某作用域的任务分配；列表为空表示全部回到继承。
     */
    TaskSettingsUpdateRequest: {
      /** Settings */
      settings: components["schemas"]["TaskSettingItem"][];
    };
    /**
     * TranslationResponse
     * @description 翻译结果响应。
     */
    TranslationResponse: {
      /** Id */
      id: string;
      /** Message Version Id */
      message_version_id: string;
      /** Status */
      status: string;
      /** Title */
      title: string | null;
      /** Summary */
      summary: string | null;
      /** Content */
      content: string | null;
      /** Provider Id */
      provider_id: string | null;
      /** Key Masked */
      key_masked: string | null;
      /** Model */
      model: string | null;
      /** Prompt Version */
      prompt_version: string;
      /** Task Id */
      task_id: string | null;
      /** Error Code */
      error_code: string | null;
      /** Error Message */
      error_message: string | null;
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_categories_api_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryResponse"][];
        };
      };
    };
  };
  create_category_api_categories_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_sources_api_sources_get: {
    parameters: {
      query?: {
        q?: string | null;
        category_id?: string | null;
        enabled?: boolean | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_source_api_sources_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_source_api_sources__source_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_source_api_sources__source_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceDeleteResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_source_api_sources__source_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourcePatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  test_source_api_sources__source_id__test_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceTestResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  source_health_api_sources__source_id__health_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_collection_run_api_collection_runs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CollectionRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_collection_run_api_collection_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionRunDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_messages_api_messages_get: {
    parameters: {
      query?: {
        q?: string | null;
        source_id?: string | null;
        keyword?: string | null;
        kind?: string | null;
        /** @description 发布时间下界，UTC 秒 */
        since?: number | null;
        /** @description 发布时间上界，UTC 秒 */
        until?: number | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_message_api_messages__message_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_message_api_messages__message_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageDeletionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  related_messages_api_messages__message_id__related_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path: {
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RelatedMessageResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  message_impact_api_messages__message_id__impact_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageDeletionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bulk_delete_messages_api_messages_bulk_delete_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MessageBulkDeleteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageDeletionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  translate_message_api_messages__message_id__translate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  enrich_message_api_messages__message_id__enrich_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_keywords_api_keywords_get: {
    parameters: {
      query?: {
        q?: string | null;
        kind?: string | null;
        /** @description 最小出现次数，1 表示包含孤词 */
        min_count?: number;
        /** @description 最近出现时间下界，UTC 秒 */
        since?: number | null;
        /** @description 最近出现时间上界，UTC 秒 */
        until?: number | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KeywordListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  keyword_overview_api_keywords_overview_get: {
    parameters: {
      query?: {
        /** @description 趋势天数，含今天 */
        days?: number;
        top_sources?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KeywordOverviewResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rebuild_index_api_keywords_rebuild_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KeywordRebuildResponse"];
        };
      };
    };
  };
  backfill_keywords_api_keywords_backfill_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KeywordBackfillRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KeywordBackfillResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_merges_api_keywords_merges_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KeywordMergeRecordResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  merge_keywords_api_keywords_merge_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KeywordMergeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KeywordMergeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  undo_merge_api_keywords_merges__merge_id__undo_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        merge_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KeywordUndoResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_task_api_tasks__task_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_task_api_tasks__task_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskDeletionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_tasks_api_tasks_get: {
    parameters: {
      query?: {
        status?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  retry_task_api_tasks__task_id__retry_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  clear_failed_tasks_api_tasks_clear_failed_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskClearFailedRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskDeletionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_providers_api_llm_providers_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderResponse"][];
        };
      };
    };
  };
  create_provider_api_llm_providers_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProviderCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_provider_api_llm_providers__provider_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProviderPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  test_provider_connection_api_llm_providers__provider_id__test_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnectionTestRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectionTestResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_provider_model_api_llm_providers__provider_id__models_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProviderModelCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderModelResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_provider_model_api_llm_providers__provider_id__models__model_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider_id: string;
        model_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProviderModelPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderModelResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_provider_key_api_llm_providers__provider_id__keys_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProviderKeyCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderKeyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_provider_key_api_llm_providers__provider_id__keys__key_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider_id: string;
        key_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProviderKeyPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderKeyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_prompts_api_llm_prompts_get: {
    parameters: {
      query?: {
        task_kind?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PromptResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_prompt_api_llm_prompts_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PromptCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PromptResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_specs_api_llm_prompts_specs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
    };
  };
  compile_prompt_template_api_llm_prompts_compile_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PromptCompileRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PromptCompileResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_prompt_api_llm_prompts__prompt_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        prompt_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PromptResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_prompt_api_llm_prompts__prompt_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        prompt_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_prompt_api_llm_prompts__prompt_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        prompt_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PromptUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PromptResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  activate_prompt_api_llm_prompts__prompt_id__activate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        prompt_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PromptResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  archive_prompt_api_llm_prompts__prompt_id__archive_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        prompt_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PromptResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_prompt_usage_api_llm_prompts__prompt_id__usage_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        prompt_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PromptUsageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  test_prompt_api_llm_prompts__prompt_id__test_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        prompt_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PromptTestRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PromptTestResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_task_settings_api_task_settings__scope___scope_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scope: string;
        scope_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskSettingResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  replace_task_settings_api_task_settings__scope___scope_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scope: string;
        scope_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskSettingsUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskSettingResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
