/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Categories */
    get: operations["list_categories_api_categories_get"];
    put?: never;
    /** Create Category */
    post: operations["create_category_api_categories_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Sources */
    get: operations["list_sources_api_sources_get"];
    put?: never;
    /** Create Source */
    post: operations["create_source_api_sources_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources/{source_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Source */
    get: operations["get_source_api_sources__source_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Source
     * @description 删除来源及其从属数据；受影响的未完成采集运行按剩余任务重算状态。
     */
    delete: operations["delete_source_api_sources__source_id__delete"];
    options?: never;
    head?: never;
    /** Update Source */
    patch: operations["update_source_api_sources__source_id__patch"];
    trace?: never;
  };
  "/api/sources/{source_id}/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Test Source */
    post: operations["test_source_api_sources__source_id__test_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources/{source_id}/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Source Health */
    get: operations["source_health_api_sources__source_id__health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collection/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Collection Run */
    post: operations["create_collection_run_api_collection_runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collection/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Collection Run
     * @description 读取所有来源汇总后的采集统计。
     */
    get: operations["get_collection_run_api_collection_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Messages */
    get: operations["list_messages_api_messages_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/messages/{message_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Message */
    get: operations["get_message_api_messages__message_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/messages/{message_id}/translate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Translate Message */
    post: operations["translate_message_api_messages__message_id__translate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Task */
    get: operations["get_task_api_tasks__task_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tasks
     * @description 查询任务列表。
     */
    get: operations["list_tasks_api_tasks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Retry Task
     * @description 重新排队失败任务。
     */
    post: operations["retry_task_api_tasks__task_id__retry_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/providers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Providers */
    get: operations["list_providers_api_llm_providers_get"];
    put?: never;
    /** Create Provider */
    post: operations["create_provider_api_llm_providers_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/providers/{provider_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Provider */
    patch: operations["update_provider_api_llm_providers__provider_id__patch"];
    trace?: never;
  };
  "/api/llm/providers/{provider_id}/keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Provider Key */
    post: operations["create_provider_key_api_llm_providers__provider_id__keys_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/providers/{provider_id}/keys/{key_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Provider Key */
    patch: operations["update_provider_key_api_llm_providers__provider_id__keys__key_id__patch"];
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * CategoryCreateRequest
     * @description 创建分类请求。
     */
    CategoryCreateRequest: {
      /** Name */
      name: string;
      /** Slug */
      slug?: string | null;
    };
    /**
     * CategoryResponse
     * @description 分类响应。
     */
    CategoryResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Is Builtin */
      is_builtin: boolean;
      /** Is Active */
      is_active: boolean;
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
    };
    /**
     * CollectionRunDetailResponse
     * @description 采集运行统计。
     */
    CollectionRunDetailResponse: {
      /** Id */
      id: string;
      /** Source Ids */
      source_ids: string[];
      /** Status */
      status: string;
      /** Requested At */
      requested_at: number;
      /** Completed At */
      completed_at: number | null;
      /** Created Count */
      created_count: number;
      /** Updated Count */
      updated_count: number;
      /** Skipped Count */
      skipped_count: number;
      /** Failed Count */
      failed_count: number;
    };
    /**
     * CollectionRunRequest
     * @description 创建采集运行请求。
     */
    CollectionRunRequest: {
      /** Source Ids */
      source_ids?: string[];
      /**
       * All Enabled
       * @default false
       */
      all_enabled: boolean;
    };
    /**
     * CollectionRunResponse
     * @description 采集运行响应。
     */
    CollectionRunResponse: {
      /** Id */
      id: string;
      /** Source Ids */
      source_ids: string[];
      /** Status */
      status: string;
      /** Requested At */
      requested_at: number;
      /** Task Ids */
      task_ids: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description 来源健康检查响应。
     */
    HealthResponse: {
      /** Id */
      id: string;
      /** Source Id */
      source_id: string;
      /** Checked At */
      checked_at: number;
      /** Http Status */
      http_status: number | null;
      /** Latency Ms */
      latency_ms: number | null;
      /** Parse Success */
      parse_success: boolean;
      /** Entry Count */
      entry_count: number;
      /** Error Code */
      error_code: string | null;
      /** Error Message */
      error_message: string | null;
    };
    /**
     * MessageDetailResponse
     * @description 消息详情响应。
     */
    MessageDetailResponse: {
      /** Id */
      id: string;
      /** Source Id */
      source_id: string;
      /** External Id */
      external_id: string;
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
      /** Versions */
      versions: components["schemas"]["MessageVersionResponse"][];
    };
    /**
     * MessageResponse
     * @description 消息列表响应。
     */
    MessageResponse: {
      /** Id */
      id: string;
      /** Source Id */
      source_id: string;
      /** External Id */
      external_id: string;
      /** Updated At */
      updated_at: number;
      latest_version: components["schemas"]["MessageVersionResponse"] | null;
    };
    /**
     * MessageVersionResponse
     * @description 消息版本响应。
     */
    MessageVersionResponse: {
      /** Id */
      id: string;
      /** Message Id */
      message_id: string;
      /** Version Number */
      version_number: number;
      /** Title */
      title: string;
      /** Summary */
      summary: string;
      /** Content */
      content: string;
      /** Url */
      url: string;
      /** Published At */
      published_at: number | null;
      /** Collected At */
      collected_at: number;
      /** Language */
      language: string;
      /** Content Hash */
      content_hash: string;
      /** Translations */
      translations: components["schemas"]["TranslationResponse"][];
      translation_task?: components["schemas"]["TaskResponse"] | null;
    };
    /**
     * ProviderCreateRequest
     * @description 创建 provider 请求。
     */
    ProviderCreateRequest: {
      /** Name */
      name: string;
      /** Base Url */
      base_url: string;
      /** Model */
      model: string;
      /**
       * Priority
       * @default 100
       */
      priority: number;
      /**
       * Timeout Seconds
       * @default 60
       */
      timeout_seconds: number;
      /** Session Header Name */
      session_header_name?: string | null;
      /** Extra Headers */
      extra_headers?: {
        [key: string]: string;
      };
    };
    /**
     * ProviderKeyCreateRequest
     * @description 创建 key 引用请求。
     */
    ProviderKeyCreateRequest: {
      /** Key Ref */
      key_ref: string;
      /**
       * Priority
       * @default 100
       */
      priority: number;
    };
    /**
     * ProviderKeyPatchRequest
     * @description 更新 key 引用请求。
     */
    ProviderKeyPatchRequest: {
      /** Priority */
      priority?: number | null;
      /** Enabled */
      enabled?: boolean | null;
    };
    /**
     * ProviderKeyResponse
     * @description key 引用响应，不包含密钥值。
     */
    ProviderKeyResponse: {
      /** Id */
      id: string;
      /** Provider Id */
      provider_id: string;
      /** Key Ref */
      key_ref: string;
      /** Priority */
      priority: number;
      /** Enabled */
      enabled: boolean;
      /** Cooldown Until */
      cooldown_until: number | null;
      /** Last Status */
      last_status: string | null;
    };
    /**
     * ProviderPatchRequest
     * @description 更新 provider 请求。
     */
    ProviderPatchRequest: {
      /** Name */
      name?: string | null;
      /** Base Url */
      base_url?: string | null;
      /** Model */
      model?: string | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Priority */
      priority?: number | null;
      /** Timeout Seconds */
      timeout_seconds?: number | null;
      /** Session Header Name */
      session_header_name?: string | null;
      /** Extra Headers */
      extra_headers?: {
        [key: string]: string;
      };
    };
    /**
     * ProviderResponse
     * @description provider 响应。
     */
    ProviderResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Base Url */
      base_url: string;
      /** Model */
      model: string;
      /** Enabled */
      enabled: boolean;
      /** Priority */
      priority: number;
      /** Timeout Seconds */
      timeout_seconds: number;
      /** Session Header Name */
      session_header_name: string | null;
      /** Keys */
      keys: components["schemas"]["ProviderKeyResponse"][];
      /** Extra Headers */
      extra_headers: {
        [key: string]: string;
      };
    };
    /**
     * SourceCreateRequest
     * @description 创建来源请求。
     */
    SourceCreateRequest: {
      /** Name */
      name: string;
      /** Url */
      url: string;
      /**
       * Platform
       * @default
       */
      platform: string;
      /**
       * Language
       * @default auto
       */
      language: string;
      /** Category Id */
      category_id: string;
      /**
       * Time Offset Minutes
       * @default 0
       */
      time_offset_minutes: number;
    };
    /**
     * SourceDeleteResponse
     * @description 删除来源响应；deleted_messages 为随之删除的消息条数。
     */
    SourceDeleteResponse: {
      /** Deleted Messages */
      deleted_messages: number;
    };
    /**
     * SourceDetailResponse
     * @description 来源详情响应。
     */
    SourceDetailResponse: {
      source: components["schemas"]["SourceResponse"];
      /** Health */
      health: components["schemas"]["HealthResponse"][];
      /**
       * Message Count
       * @default 0
       */
      message_count: number;
      latest_collection?:
        components["schemas"]["CollectionRunDetailResponse"] | null;
    };
    /**
     * SourceListResponse
     * @description 来源列表响应；total 是当前过滤条件下的总数，与 items 的分页窗口无关。
     */
    SourceListResponse: {
      /** Items */
      items: components["schemas"]["SourceResponse"][];
      /** Total */
      total: number;
    };
    /**
     * SourcePatchRequest
     * @description 更新来源请求。
     */
    SourcePatchRequest: {
      /** Name */
      name?: string | null;
      /** Url */
      url?: string | null;
      /** Platform */
      platform?: string | null;
      /** Language */
      language?: string | null;
      /** Category Id */
      category_id?: string | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Time Offset Minutes */
      time_offset_minutes?: number | null;
    };
    /**
     * SourceResponse
     * @description 来源响应。
     */
    SourceResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Url */
      url: string;
      /** Platform */
      platform: string;
      /** Language */
      language: string;
      /** Category Id */
      category_id: string;
      /** Enabled */
      enabled: boolean;
      /** Time Offset Minutes */
      time_offset_minutes: number;
      /** Feed Title */
      feed_title: string | null;
      /** Feed Link */
      feed_link: string | null;
      /** Feed Description */
      feed_description: string | null;
      /** Feed Language */
      feed_language: string | null;
      /** Feed Author */
      feed_author: string | null;
      /** Feed Updated At */
      feed_updated_at: string | null;
      /** Source Type */
      source_type: string;
      /** Metadata */
      metadata: {
        [key: string]: unknown;
      };
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
      latest_health?: components["schemas"]["HealthResponse"] | null;
      /** Last Success At */
      last_success_at?: number | null;
    };
    /**
     * SourceTestResponse
     * @description 来源测试响应。
     */
    SourceTestResponse: {
      source: components["schemas"]["SourceResponse"];
      health: components["schemas"]["HealthResponse"];
    };
    /**
     * TaskResponse
     * @description 任务状态响应。
     */
    TaskResponse: {
      /** Id */
      id: string;
      /** Task Type */
      task_type: string;
      /** Idempotency Key */
      idempotency_key: string;
      /** Status */
      status: string;
      /** Attempts */
      attempts: number;
      /** Lease Until */
      lease_until: number | null;
      /** Input Version Id */
      input_version_id: string | null;
      /** Output Version Id */
      output_version_id: string | null;
      /** Error Code */
      error_code: string | null;
      /** Error Message */
      error_message: string | null;
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
    };
    /**
     * TranslationResponse
     * @description 翻译结果响应。
     */
    TranslationResponse: {
      /** Id */
      id: string;
      /** Message Version Id */
      message_version_id: string;
      /** Status */
      status: string;
      /** Title */
      title: string | null;
      /** Summary */
      summary: string | null;
      /** Content */
      content: string | null;
      /** Provider Id */
      provider_id: string | null;
      /** Key Ref */
      key_ref: string | null;
      /** Model */
      model: string | null;
      /** Prompt Version */
      prompt_version: string;
      /** Task Id */
      task_id: string | null;
      /** Error Code */
      error_code: string | null;
      /** Error Message */
      error_message: string | null;
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_categories_api_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryResponse"][];
        };
      };
    };
  };
  create_category_api_categories_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_sources_api_sources_get: {
    parameters: {
      query?: {
        q?: string | null;
        category_id?: string | null;
        enabled?: boolean | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_source_api_sources_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_source_api_sources__source_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_source_api_sources__source_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceDeleteResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_source_api_sources__source_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourcePatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  test_source_api_sources__source_id__test_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceTestResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  source_health_api_sources__source_id__health_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_collection_run_api_collection_runs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CollectionRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_collection_run_api_collection_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionRunDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_messages_api_messages_get: {
    parameters: {
      query?: {
        q?: string | null;
        source_id?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_message_api_messages__message_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  translate_message_api_messages__message_id__translate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_task_api_tasks__task_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_tasks_api_tasks_get: {
    parameters: {
      query?: {
        status?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  retry_task_api_tasks__task_id__retry_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_providers_api_llm_providers_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderResponse"][];
        };
      };
    };
  };
  create_provider_api_llm_providers_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProviderCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_provider_api_llm_providers__provider_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProviderPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_provider_key_api_llm_providers__provider_id__keys_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProviderKeyCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderKeyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_provider_key_api_llm_providers__provider_id__keys__key_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider_id: string;
        key_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProviderKeyPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderKeyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
